### PR TITLE
Add voting list in post summary, voting rate

### PR DESCRIPTION
**Pull request by realmankwon**
Add voting list in post summary, voting rate

image

### CODE REVIEW

**Comment by eonwarped** [comment]
This is fine with me, as long that is what you want to expose.

By the way, are you going to separate the voting estimate? I might add that back when i have time to do so. With recent changes I have loaded the scot curation curve info into the state.app, so that should be useful.

**Comment by realmankwon** [comment]
> This is fine with me, as long that is what you want to expose.
> 
> By the way, are you going to separate the voting estimate? I might add that back when i have time to do so. With recent changes I have loaded the scot curation curve info into the state.app, so that should be useful.

I did it with the formula you gave me but the results were still wrong, so I split it up and corrected it. But I would like to apply it in relation.

And one more question. I want to show steem expected payout together. However, pages such as Trending, hot can not bring the value of steem and it is displayed as NaN. When I first got the nitrous source, all of my pages had normal values, but then source pulled and did not show up after steemApi.js was changed. I wonder how I can get steam data out of every page.

**Comment by realmankwon** [comment]
> This is fine with me, as long that is what you want to expose.
> 
> By the way, are you going to separate the voting estimate? I might add that back when i have time to do so. With recent changes I have loaded the scot curation curve info into the state.app, so that should be useful.

hi, @eonwarped !!

Can you tell me how to use the scot curation curve? What parameters should I enter in state.app.get?

**Comment by eonwarped** [comment]
If you do

`const scotConfig = state.app.get('scotConfig');`

you can do

`scotConfig.getIn(['config', 'curation_curve_exponent']`

for example, and anything that you might find in https://scot-api.steem-engine.com/config?token=SCT

Regarding STEEM payouts, I was working on it, and then realized that it's not compatible with the scot api without having to do double-fetches everywhere. The way to go is to get @holger80 to populate the STEEM data along with the other token data into the scot API, I feel.

**Comment by eonwarped** [comment]
Also see https://steemit.com/steem-engine/@holger80/code-optimizations-for-scotbot  for how to compute the estimate.

**Comment by realmankwon** [comment]
> Also see https://steemit.com/steem-engine/@holger80/code-optimizations-for-scotbot for how to compute the estimate.


I recalculated with reference to your posting link. However, the data still displayed is different from the total expected payout. I think the first one I did (voter.rshares / total_rshares) is correct. I would like you to give me the exact formula again.

            scotPendingShares : scotConfig.getIn(['info', 'pending_rshares'], 0),
            scotRewardPool : scotConfig.getIn(['info', 'reward_pool'], 0),
            scotAuthorCurveExponent : scotConfig.getIn(['config', 'author_curve_exponent'], 0),


             const voter_pending_token = Math.pow(rshares, scotAuthorCurveExponent) / scotPendingShares * scotRewardPool / scotDenom;
                
                voters.push({
                    value: (sign > 0 ? '+ ' : '- ') + voter
                            + ' (' + percent / 100 + '%) '
                            + voter_pending_token.toFixed(2) + ' ' + LIQUID_TOKEN_UPPERCASE,
                    link: '/@' + voter,
                });

image

**Pull request merged**
