### PR TITLE
Scotty steemcoinpan

### PR DESCRIPTION
**Pull request by realmankwon**
1. Add Voting Rate
- Exclude expected price of voter
- Remove total voter count in VotesAndComment.jsx (add show totalVotes parameter)

image

2. Change Voting Slide Bar

image

3. Add SCOT Token Balances in Wallet
-Sort alphabetically in ascending order and exclude the same token as LIQUID_TOKEN_UPPERCASE

image

Question)
I have changed expected voting price logic, but result is wrong.

       let total_weighted_rshares = 0;
       let curr_rshare_sum = 0;

       for (var i=0; i < avotes.length; i++) {
            total_weighted_rshares += (curr_rshare_sum + avotes[i].rshares )^1.3;
            curr_rshare_sum += avotes[i].rshares;
        }

       curr_rshare_sum = 0;
       for (var i=0; i < avotes.length; i++) {
            avotes[i].price_of_voter = ( (curr_rshare_sum + avotes[i].rshares )^1.3 - curr_rshare_sum^1.3 ) / total_weighted_rshares * payout;
            curr_rshare_sum += avotes[i].rshares;
        }

image

and In the voting list sorting logic, it was simply sorted by rshares, but is not rshares already calculated in 1.3?

I am willing to revise this part if I know only the correct calculation method.

### CODE REVIEW

**Comment by eonwarped** [comment]
Oh don't actually use ^, use Math,pow, I suspect that's the cause.

**Comment by realmankwon** [comment]
> Oh don't actually use ^, use Math,pow, I suspect that's the cause.

I got it. :)

**Comment by realmankwon** [comment]
> Oh don't actually use ^, use Math,pow, I suspect that's the cause.

I have changed the code, but the result is still wrong.

image

           let total_weighted_rshares = 0;
            let curr_rshare_sum = 0;
         
             for (var i=0; i < avotes.length; i++) {
                 total_weighted_rshares += Math.pow(curr_rshare_sum + avotes[i].rshares, 1.3);
                 curr_rshare_sum += avotes[i].rshares;
             }
         
             curr_rshare_sum = 0;
             for (var i=0; i < avotes.length; i++) {
                 avotes[i].price_of_voter = (( Math.pow(curr_rshare_sum + avotes[i].rshares, 1.3) - Math.pow(curr_rshare_sum, 1.3)) 
                                             / total_weighted_rshares * payout).toFixed(2);
                 curr_rshare_sum += avotes[i].rshares;
             }

Is there anything I've done wrong?

**Comment by realmankwon** [comment]
> Oh don't actually use ^, use Math,pow, I suspect that's the cause.

I have changed the code, but the result is still wrong.

image

           let total_weighted_rshares = 0;
            let curr_rshare_sum = 0;
         
             for (var i=0; i < avotes.length; i++) {
                 total_weighted_rshares += Math.pow(curr_rshare_sum + avotes[i].rshares, 1.3);
                 curr_rshare_sum += avotes[i].rshares;
             }
         
             curr_rshare_sum = 0;
             for (var i=0; i < avotes.length; i++) {
                 avotes[i].price_of_voter = (( Math.pow(curr_rshare_sum + avotes[i].rshares, 1.3) - Math.pow(curr_rshare_sum, 1.3)) 
                                             / total_weighted_rshares * payout).toFixed(2);
                 curr_rshare_sum += avotes[i].rshares;
             }

Is there anything I've done wrong?

**Comment by realmankwon** [comment]
> Oh don't actually use ^, use Math,pow, I suspect that's the cause.

Are other modifications applicable except expected voting price logic?

**Comment by eonwarped** [comment]
Yes, (Btw can you put this in the PR so i can comment directly?)

```
 for (var i=0; i < avotes.length; i++) {
             total_weighted_rshares += Math.pow(/* REMOVEME curr_rshare_sum + */ avotes[i].rshares, 1.3);
             // REMOVE THIS!!!  curr_rshare_sum += avotes[i].rshares;
         }
```

In the first loop, remove curr_Rshare and the parts i commented above.

**Pull request closed without merging**
