### PR TITLE
add dynamic topics sidebar, and sportstube link

### PR DESCRIPTION
**Pull request by voltairez**
### Features

1. in left sidebar, show the children categories for the currently selected category
1. in right sidebar, add the link to SportsTube

### Screenshots

1. show children categories

e.g. in page https://sportstalk-social.herokuapp.com/trending/football, show sub-categories:

pic

2. add the SportsTube link

pic

### Code Change

**Dynamic Topics**
1. In `PostInde.jsx`, search and build the categories tree based on the current category;
1. In `Topics.jsx`, show max level of topics and fix some issues
1. In `client_config.js`, add the categories

**SportsTube Link**
1. Modify `SidebarLinks`, `Icon`, locaes 
1. Add one logo for dtube

### Test

- https://sportstalk-social.herokuapp.com/trending/football

### Future Plan

1. Add logos for topics to make the look and feel better;
1. Show posts in all descendant categories for current category.

### CODE REVIEW

**Comment by voltairez** [comment]
@patrickulrich Patrick has reviewed the feature and test already. 

@eonwarped Hi eon, could you please help with the review?

**Comment by voltairez** [comment]
@eonwarped Hi eon, could you please help check (and maybe fix if know the cause) the PR if can see the details about why it failed? I cannot find the travis build log for this failure.

**Comment by eonwarped** [comment]
I think that's not relevant. But if you ran it locally, then it should be fine and I can try merging it in.

**Comment by eonwarped** [comment]
Will merge in. If there are any issues, I can also revert quickly in heroku. It looks okay at a glance.

**Comment by voltairez** [comment]
@eonwarped we have tested here: https://sportstalk-social.herokuapp.com  

could you please help confirm and let us know for any suggestions?

**Comment by voltairez** [comment]
@eonwarped ok. just saw it's merged. and it seems https://www.sportstalksocial.com works quite well. thanks a lot!

**Pull request merged**
