### PR TITLE
add the search feature according to the requests of SCT team

### PR DESCRIPTION
**Pull request by think-in-universe**
### Description
The requirements of the search feature can be found in this post: https://www.steemcoinpan.com/sct/@sct.tom/steemcoinpan

### Preview
You can preview the feature in our test site: https://sctcn.herokuapp.com/

### Status
This PR includes the below features:
1. enable Custom Google Search for steemcoinpan, which is similar to the steemit.com search
1. add the preview feature for search results 

### To Do
1. add the feature of paying 1 SCT (and reward 0.7 to author, and burn 0.3) when the user click the post

### Contributor
- we're from a developer group in CN community
- developers' steem accounts:   ericet,   robertyan

### CODE REVIEW

**Comment by passionbull** [comment]
I went into the website and tried to use the features.
It overall works well. 

I want to comment suggestion and bug I found.

1. If an image is at the front on content, only the image is visible. I think it would be okay to look at the preview without the image.

2. This function sometimes don't show preview of content. (if search result is not content, it dont show preview)
    - I searched "sey" , "wallet"

Thank you!

**Comment by think-in-universe** [comment]
@passionbull 

great feedback.

- for issue 1, yes, I also thought that's helpful to remove the images.
- for issue 2, it's a bit tricky, and I knew the problem. Actually, I firstly tried to load the preview with iframe, but it seems disallowed by the nitrous project's configuration. Now we're using steem.js to call the content and render the post from markdown.
  - so to implement issue 2, we may review whether it's able to preview with iframe again or other solutions. The page like "user profile", "transfer", etc. are not markdown source, and should be rendered as html directly.

**Comment by eonwarped** [comment]
This looks fine to me, feel free to merge in @passionbull

**Comment by think-in-universe** [comment]
here are more suggestions from steemcoinpan team: 

steemcoinpan team discuss about search function and suggest some ideas.

1. Summary should be text, not image.
2. If result of search shows the past compensation value of the article author, the reliability will increase.
3. When a user selects a search result, a comment with an evaluation table formatted is automatically created.
    - steemcoinpan team will vote the 2sct equivalent of the vote on the comment.
4. The title of a search result article is displayed as it is, without omitting it. (no display ...)
5. it is better to be able to set the search period.
6. it would be helpful if there was a first posting date
7. It would be more convenient if website add new window for link when you click link. ('open link in new window')
8. This function sometimes don't show preview of content. (if search result is not content, it dont show preview)
9. It would be nice if there was a reputation system. (such as welcome, family, vip, vvip)
ex) a post is selected many times, reputation of author that wrote the post become vip.

**Comment by think-in-universe** [comment]
Actions from @robertyan:

- [x] fix the image display issue
- [ ] add the "pay when select post" feature.

More enhancements:
- [ ] add "a comment with an evaluation table formatted"

**Comment by passionbull** [comment]
Thank you for your contribution.

I think these should be done first.

- if a user search and selected post, paid 1sct.
- and then a user write automatically comment on the selected post.
- steem coinpan team should vote the comment.

I thinks (1), (3) is high properties.

**Comment by think-in-universe** [comment]
Close this PR, since we're moving the work into a new one: https://github.com/steem-engine-exchange/nitrous/pull/48

**Pull request closed without merging**
